types <- list(
  weight_types = c("Carli", 
                   "Dutot",
                   "Laspeyres",
                   "HybridLaspeyres",
                   "Paasche",
                   "HybridPaasche",
                   "Palgrave", 
                   "Unnamed", 
                   "Drobish", 
                   "Walsh1", 
                   "MarshallEdgeworth", 
                   "GearyKhamis",
                   "Jevons",
                   "Tornqvist",
                   "SatoVartia",
                   "Vartia2",
                   "Walsh2",
                   "Lowe",
                   "Young",
                   "Coggeshall"),
  
  arithmetic_index_types = c("Carli", 
                             "Dutot",
                             "Laspeyres",
                             "Palgrave", 
                             "Unnamed", 
                             "Drobish", 
                             "Walsh1", 
                             "MarshallEdgeworth", 
                             "GearyKhamis",
                             "Lowe",
                             "Young"),
  
  geometric_index_types = c("Jevons",
                            "Laspeyres",
                            "Paasche", 
                            "Young",
                            "Tornqvist",
                            "SatoVartia",
                            "Vartia2",
                            "Walsh2"),
  
  harmonic_index_types = c("Coggeshall",
                          "Laspeyres",
                          "Paasche")
)