types <- list(
  weight_types = c("Carli",
                   "Jevons",
                   "Coggeshall",
                   "Dutot",
                   "Laspeyres",
                   "HybridLaspeyres",
                   "Palgrave",
                   "Paasche",
                   "HybridPaasche",
                   "Drobish",
                   "Unnamed",
                   "Tornqvist",
                   "Walsh1",
                   "Walsh2",
                   "MarshallEdgeworth",
                   "GearyKhamis",
                   "Vartia1",
                   "MontgomeryVartia",
                   "Vartia2",
                   "SatoVartia",
                   "Lowe",
                   "Young",
                   "LloydMoulton"),
  arithmetic_index_types = c("Carli",
                             "Dutot",
                             "Laspeyres",
                             "Palgrave",
                             "Drobish",
                             "Unnamed",
                             "Walsh1",
                             "MarshallEdgeworth",
                             "GearyKhamis"),
  geometric_index_types = c("Jevons",
                            "Laspeyres",
                            "Paasche",
                            "Tornqvist",
                            "Vartia1",
                            "MontgomeryVartia",
                            "Vartia2",
                            "SatoVartia",
                            "Walsh2"),
  harmonic_index_types = c("Coggeshall",
                           "Laspeyres",
                           "Paasche")
)